
        
        {location: "40.701534, -73.935887",
        address: "10 Montieth St, Brooklyn, NY 11206",
        description: "This penthouse apartment offers the luxury of the recently constructed Rheingold and the best views available in this part of Brooklyn. Packed with Amenities, you may never need to leave the building!"
        lister_id: 1,
        building_id: 1,
        unit: 10,
        rental: true,
        price: 5500,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Brooklyn"},
        
        {location: "40.701534, -73.935887",
        address: "10 Montieth St, Brooklyn, NY 11206",
        description: "This spacious two-bedroom is for sale in the gorgeous Rheingold building. Overlooking a small park the the south, this apartment comes furnished, having recently been remodeled to update the kitchen, bathrooms, lighting, and appliances."
        lister_id: 2,
        building_id: 1,
        unit: 8,
        rental: false,
        price: 3000000,
        num_baths: 2,
        num_bedrooms: 2,
        borough: "Brooklyn"},

        {location: "40.701534, -73.935887",
        address: "10 Montieth St, Brooklyn, NY 11206",
        description: "Find yourself at home in this large 3 bedroom apartment for rent in the luxurious Rhenigold building in the heart of Bushwick. Appointed in white marble and oak, this space has recently been remodeled with new tenants in mind."
        lister_id: 2,
        building_id: 1,
        unit: 6,
        rental: true,
        price: 8500,
        num_baths: 2,
        num_bedrooms: 3,
        borough: "Brooklyn"},
        
        {location: "40.700686, -73.933763",
        address: "54 Noll St, Brooklyn, NY 11206",
        description: "This bright, open-plan apartment is perfect for the young-professional family. Featuring a jacuzzi tub and recessed lighting, this spacious home comes fully furnished and is move-in ready!"
        lister_id: 3,
        building_id: 2,
        unit: "4A",
        rental: true,
        price: 8500,
        num_baths: 2,
        num_bedrooms: 3,
        borough: "Brooklyn"},
 
        {location: "40.700686, -73.933763",
        address: "54 Noll St, Brooklyn, NY 11206",
        description: "This large single-bedroom apartment is perfect for the aspiring young professional. Boasting 12' ceilings, a jacuzzi, and a full marble kitchen, find yourself at home in this beautiful space."
        lister_id: 1,
        building_id: 2,
        unit: "7G",
        rental: true,
        price: 7600,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Brooklyn"},

        {location: "40.700686, -73.933763",
        address: "54 Noll St, Brooklyn, NY 11206",
        description: "This windowless basement apartment is haunted by no fewer than 13 ghosts, and the apartment number randomly changes. Something nice to discuss with your therapist!"
        lister_id: 1,
        building_id: 2,
        unit: "666",
        rental: true,
        price: 6600,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Brooklyn"},
 
        {location: "40.700686, -73.933763",
        address: "54 Noll St, Brooklyn, NY 11206",
        description: "This windowless basement apartment is haunted by no fewer than 13 ghosts, and the apartment number randomly changes. Something nice to discuss with your therapist!"
        lister_id: 1,
        building_id: 2,
        unit: "666",
        rental: true,
        price: 6600,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Brooklyn"},
        
        {location: "40.609968447836366, -74.07040613037246"
        address: "14 Thompson Pl, Staten Island, NY 10305"
        description: "This three story apartment building is for sale in the quiet residential neighborhood of "
        lister_id: 1,
        building_id: nil,
        unit: "1-12",
        rental: false,
        price: 7290000,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Staten Island"},

        {location: "40.699439, -73.933427",
        address: "123 Melrose St, Brooklyn, NY 11206",
        description: "This spacious two bedroom apartment, currently owned by an undisclosed A-list film star, can be yours now. Fully furnished and recently remodeled, the space will feel like home the moment step inside."
        lister_id: 1,
        building_id: 4,
        unit: "11",
        rental: true,
        price: 11000,
        num_baths: 1,
        num_bedrooms: 2,
        borough: "Brooklyn"},

        {location: "40.699439, -73.933427",
        address: "123 Melrose St, Brooklyn, NY 11206",
        description: "This enormous penthouse apartment can be yours to own. From the heart of Brooklyn, your rooftop patio breakfast nook overlooks downtown, the river, and the financial district, and boasts floor to cieling glass and all-marble floors."
        lister_id: 1,
        building_id: 4,
        unit: "P",
        rental: false,
        price: 9100000,
        num_baths: 2,
        num_bedrooms: 3,
        borough: "Brooklyn"},

        {location: "40.699439, -73.933427",
        address: "123 Melrose St, Brooklyn, NY 11206",
        description: "This elegant apartment is the perfect home for the ambitious young professional. Let the address elevate your reputation while this modern home and luxury building elevate your wellbeing."
        lister_id: 1,
        building_id: 4,
        unit: "",
        rental: true,
        price: 8700,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Brooklyn"},
        
        {location: "40.738349, -73.973471",
        address: "30 Waterside Plaza, New York, NY 10010",
        description: "If you have never lived in a luxury rental, this apartment will make you wonder why. Smart home integration, polished marble, and floor to cieling windows overlooking the East River complement the amenities offered in the building's common areas."
        lister_id: 1,
        building_id: 5,
        unit: "21",
        rental: true,
        price: 8400,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Brooklyn"}


        {location: "40.738349, -73.973471",
        address: "30 Waterside Plaza, New York, NY 10010",
        description: "In the luxury building nestled in the heart of Brooklyn, in this elegant 3 bedroom home, you will know only peace and quiet. Any amenity not in the unit is available in the building, such that you hardly need to leave."
        lister_id: 1,
        building_id: 5,
        unit: "14",
        rental: true,
        price: 12500,
        num_baths: 2,
        num_bedrooms: 3,
        borough: "Brooklyn"},


        {location: "40.738349, -73.973471",
        address: "30 Waterside Plaza, New York, NY 10010",
        description: "Four walls and a roof. No floor guaranteed. Look out below!"
        lister_id: 1,
        building_id: 5,
        unit: "21",
        rental: true,
        price: 8400,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Brooklyn"},

        # --------------   end of buildings-grouped listings ---------------
        
        {location: "40.639035, -73.964566",
        address: "433 Rugby Rd, Brooklyn, NY 11226",
        description: "This charming woodframe house has 200 years of history in its walls. On a quiet residential street, and near the restaurants and bars on Cortelyou, this location is perfect for families or work-from-homers.",
        lister_id: 2,
        building_id: 9,
        unit: "bob",
        rental: false,
        price: 2300000,
        num_baths: 3,
        num_bedrooms: 4,
        borough: "Brooklyn"},
        
        {location: "40.667640, -73.943060",
        address: "1405-1349 President St, Brooklyn, NY 11213",
        description: "This modern apartment will make a perfect home base for a young professional. With amenities like a fitness center, doorman, pet grooming service, and full service laundry, this elegant complex is clean and luxurious.",
        lister_id: 1,
        building_id: 9,
        unit: "D",
        rental: true,
        price: 3500,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Brooklyn"},
        
        {location: "40.694692, -73.915836",
        address: "210 Palmetto St, Brooklyn, NY 11221",
        description: "This two-bedroom apartment rests on a quiet street in a hip neighborhood. Just a block from bars and shops, as well as a local bagel mecca, this apartment will be the home in Bushwick that you'll remember forever.",
        lister_id: 2,
        building_id: 9,
        unit: "3D",
        rental: true,
        price: 2900,
        num_baths: 1, 
        num_bedrooms: 2, 
        borough: "Brooklyn"},
        
        {location: "40.731768, -73.960618",
        address: "21 India St, Brooklyn, NY 11222",
        description: "This is the penthouse apartment in the luxurious The Greenpoint building.",
        lister_id: 2,
        building_id: 9,
        unit: 5,
        rental: true,
        price: 5600,
        num_baths: 1,
        num_bedrooms: 2,
        borough: "Brooklyn"},
        
        {location: "40.731768, -73.960618",
        address: "21 India St, Brooklyn, NY 11222",
        description: "This is the first floor apartment in the luxurious The Greenpoint building.",
        lister_id: 2,
        building_id: 9,
        unit: 1,
        rental: true,
        price: 4100,
        num_baths: 2,
        num_bedrooms: 2,
        borough: "Brooklyn"},
        
        {location: "40.625662, -74.024179",
        address: "8001 5th Ave, Brooklyn, NY 11209",
        description: "This lovely second floor apartment is perched above a deli in the heart of Bay Ridge. This quiet location is moments from the water to the west, and a few minutes walk from greenery to the north.", 
        lister_id: 1,
        building_id: 9,
        unit: 2,
        rental: true,
        price: 3500,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Brooklyn"},
        
        {location: "40.644747, -74.003469",
        address: "4419 7th Ave, Brooklyn, NY 11220",
        description: "This basement apartment was once a mortuary, then a crypt. Happy halloween, renter.",
        lister_id: 1,
        building_id: 9,
        unit: "A",
        rental: true,
        price: 5500,
        num_baths: 1,
        num_bedrooms: 2,
        borough: "Brooklyn"},
        
        
        {location: "40.719591, -73.770056",
        address: "193-23 Salerno Ave, Queens, NY 11423" ,
        description: "A quiet, residential street will bring you the New York experience you didn't know you wanted. Tucked away is Holliswood, this bungalow will become your calm sanctuary in the busy city",
        lister_id: 2,
        building_id: 9,
        unit: "bob",
        rental: false,
        price: 20000000,
        num_baths: 3,
        num_bedrooms: 5,
        borough: "Queens"},
        
        
        {location: "40.733876, -73.775290",
        address: "73-61 196th Pl, Queens, NY 11366",
        description: "This suburban ranch house will make you believe you are living far away from the big city. One one fifth acre of well kept grass, this house is availabe on a two year lease to the right tenant.",
        lister_id: 2,
        building_id: 9,
        unit: "bob",
        rental: true,
        price: 6500,
        num_baths: 2,
        num_bedrooms: 3,
        borough: "Queens"},
        
        {location: "40.782808, -73.838649",
        address: "18-14 130th St, Flushing, NY 11356",
        description: "This converted loft will be the envy of your visitors. A former tombstone factory, this space boasts 20 foot cielings, industrial skylights, brick walls, polished concrete flooring, and more square footage than you can shake a sofa at. ",
        lister_id: 1,
        building_id: 9,
        unit: "bob",
        rental: true,
        price: 8900,
        num_baths: 1,
        num_bedrooms: 1,
        borough: "Queens"}
    

    



